### ISSUE TITLE
Connect domain hawk.art.br to shopify

### ISSUE THREAD

**Issue by ViniciusmDias** [impuls-e/hawk#35]
- [ ] Connect domain hawk.art.br to shopify and set it as primary

https://help.shopify.com/pt-BR/manual/domains/add-a-domain/using-existing-domains/connecting-domains#add-an-existing-domain-to-your-shopify-store

**Comment by jbastosufsc** [comment]
Aguardando a transição para continuar o procedimento

![Screenshot from 2020-04-28 15-29-40](https://user-images.githubusercontent.com/6197055/80523864-1d083200-8965-11ea-9a1b-d24267858fb6.png)
